name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install FLINT (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libflint-dev
    
    - name: Install FLINT (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install flint
    
    - name: configure
      run: ./configure
    
    - name: make
      run: make
    
    - name: make check
      run: make check
